/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl.myDsl.GroupStatement;
import org.xtext.example.mydsl.myDsl.IfStatement;
import org.xtext.example.mydsl.myDsl.InboundEndpointDef;
import org.xtext.example.mydsl.myDsl.LoopStatement;
import org.xtext.example.mydsl.myDsl.MediatorStatement;
import org.xtext.example.mydsl.myDsl.Model;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.OutboundEndpointDef;
import org.xtext.example.mydsl.myDsl.ParallelStatement;
import org.xtext.example.mydsl.myDsl.ParticipantStatement;
import org.xtext.example.mydsl.myDsl.ProcessingStatement;
import org.xtext.example.mydsl.myDsl.RefStatement;
import org.xtext.example.mydsl.myDsl.RoutingStatement;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MyDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MyDslPackage.GROUP_STATEMENT:
				sequence_GroupStatement(context, (GroupStatement) semanticObject); 
				return; 
			case MyDslPackage.IF_STATEMENT:
				sequence_IfStatement(context, (IfStatement) semanticObject); 
				return; 
			case MyDslPackage.INBOUND_ENDPOINT_DEF:
				sequence_InboundEndpointDef(context, (InboundEndpointDef) semanticObject); 
				return; 
			case MyDslPackage.LOOP_STATEMENT:
				sequence_LoopStatement(context, (LoopStatement) semanticObject); 
				return; 
			case MyDslPackage.MEDIATOR_STATEMENT:
				sequence_MediatorStatement(context, (MediatorStatement) semanticObject); 
				return; 
			case MyDslPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case MyDslPackage.OUTBOUND_ENDPOINT_DEF:
				sequence_OutboundEndpointDef(context, (OutboundEndpointDef) semanticObject); 
				return; 
			case MyDslPackage.PARALLEL_STATEMENT:
				sequence_ParallelStatement(context, (ParallelStatement) semanticObject); 
				return; 
			case MyDslPackage.PARTICIPANT_STATEMENT:
				sequence_ParticipantStatement(context, (ParticipantStatement) semanticObject); 
				return; 
			case MyDslPackage.PROCESSING_STATEMENT:
				sequence_ProcessingStatement(context, (ProcessingStatement) semanticObject); 
				return; 
			case MyDslPackage.REF_STATEMENT:
				sequence_RefStatement(context, (RefStatement) semanticObject); 
				return; 
			case MyDslPackage.ROUTING_STATEMENT:
				sequence_RoutingStatement(context, (RoutingStatement) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Statement returns GroupStatement
	 *     GroupStatement returns GroupStatement
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_GroupStatement(ISerializationContext context, GroupStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.GROUP_STATEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.GROUP_STATEMENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getGroupStatementAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Statement returns IfStatement
	 *     IfStatement returns IfStatement
	 *
	 * Constraint:
	 *     (routeId=STRING transport=STRING pattern=STRING altstatements+=Statement* elsestatements+=Statement*)
	 */
	protected void sequence_IfStatement(ISerializationContext context, IfStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     InboundEndpointDef returns InboundEndpointDef
	 *
	 * Constraint:
	 *     (protocol=STRING port=INT context=STRING)
	 */
	protected void sequence_InboundEndpointDef(ISerializationContext context, InboundEndpointDef semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.INBOUND_ENDPOINT_DEF__PROTOCOL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.INBOUND_ENDPOINT_DEF__PROTOCOL));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.INBOUND_ENDPOINT_DEF__PORT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.INBOUND_ENDPOINT_DEF__PORT));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.INBOUND_ENDPOINT_DEF__CONTEXT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.INBOUND_ENDPOINT_DEF__CONTEXT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getInboundEndpointDefAccess().getProtocolSTRINGTerminalRuleCall_4_0(), semanticObject.getProtocol());
		feeder.accept(grammarAccess.getInboundEndpointDefAccess().getPortINTTerminalRuleCall_9_0(), semanticObject.getPort());
		feeder.accept(grammarAccess.getInboundEndpointDefAccess().getContextSTRINGTerminalRuleCall_14_0(), semanticObject.getContext());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Statement returns LoopStatement
	 *     LoopStatement returns LoopStatement
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_LoopStatement(ISerializationContext context, LoopStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.LOOP_STATEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.LOOP_STATEMENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLoopStatementAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Statement returns MediatorStatement
	 *     MediatorStatement returns MediatorStatement
	 *
	 * Constraint:
	 *     (mediatorStatement=MediatorType config=STRING)
	 */
	protected void sequence_MediatorStatement(ISerializationContext context, MediatorStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.MEDIATOR_STATEMENT__MEDIATOR_STATEMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.MEDIATOR_STATEMENT__MEDIATOR_STATEMENT));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.MEDIATOR_STATEMENT__CONFIG) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.MEDIATOR_STATEMENT__CONFIG));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMediatorStatementAccess().getMediatorStatementMediatorTypeEnumRuleCall_0_0(), semanticObject.getMediatorStatement());
		feeder.accept(grammarAccess.getMediatorStatementAccess().getConfigSTRINGTerminalRuleCall_2_0(), semanticObject.getConfig());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     (participants+=ParticipantStatement | statements+=Statement)+
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     OutboundEndpointDef returns OutboundEndpointDef
	 *
	 * Constraint:
	 *     (protocol=STRING host=STRING)
	 */
	protected void sequence_OutboundEndpointDef(ISerializationContext context, OutboundEndpointDef semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.OUTBOUND_ENDPOINT_DEF__PROTOCOL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.OUTBOUND_ENDPOINT_DEF__PROTOCOL));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.OUTBOUND_ENDPOINT_DEF__HOST) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.OUTBOUND_ENDPOINT_DEF__HOST));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOutboundEndpointDefAccess().getProtocolSTRINGTerminalRuleCall_4_0(), semanticObject.getProtocol());
		feeder.accept(grammarAccess.getOutboundEndpointDefAccess().getHostSTRINGTerminalRuleCall_9_0(), semanticObject.getHost());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Statement returns ParallelStatement
	 *     ParallelStatement returns ParallelStatement
	 *
	 * Constraint:
	 *     (parstatements+=Statement* elsestatements+=Statement*)
	 */
	protected void sequence_ParallelStatement(ISerializationContext context, ParallelStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ParticipantStatement returns ParticipantStatement
	 *
	 * Constraint:
	 *     ((name=ID participantType=ParticipantType description=STRING) | (name=ID outbounds=OutboundEndpointDef) | (name=ID inbounds=InboundEndpointDef))
	 */
	protected void sequence_ParticipantStatement(ISerializationContext context, ParticipantStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ProcessingStatement returns ProcessingStatement
	 *
	 * Constraint:
	 *     (name=ID configs=STRING?)
	 */
	protected void sequence_ProcessingStatement(ISerializationContext context, ProcessingStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Statement returns RefStatement
	 *     RefStatement returns RefStatement
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_RefStatement(ISerializationContext context, RefStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.REF_STATEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.REF_STATEMENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRefStatementAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Statement returns RoutingStatement
	 *     RoutingStatement returns RoutingStatement
	 *
	 * Constraint:
	 *     (source=ID target=ID action=STRING)
	 */
	protected void sequence_RoutingStatement(ISerializationContext context, RoutingStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.ROUTING_STATEMENT__SOURCE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.ROUTING_STATEMENT__SOURCE));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.ROUTING_STATEMENT__TARGET) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.ROUTING_STATEMENT__TARGET));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.ROUTING_STATEMENT__ACTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.ROUTING_STATEMENT__ACTION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRoutingStatementAccess().getSourceIDTerminalRuleCall_0_0(), semanticObject.getSource());
		feeder.accept(grammarAccess.getRoutingStatementAccess().getTargetIDTerminalRuleCall_2_0(), semanticObject.getTarget());
		feeder.accept(grammarAccess.getRoutingStatementAccess().getActionSTRINGTerminalRuleCall_4_0(), semanticObject.getAction());
		feeder.finish();
	}
	
	
}
