/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.MediatorStatement;
import org.xtext.example.mydsl.myDsl.MediatorType;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Mediator Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.MediatorStatementImpl#getMediatorStatement <em>Mediator Statement</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.MediatorStatementImpl#getConfig <em>Config</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MediatorStatementImpl extends StatementImpl implements MediatorStatement
{
  /**
   * The default value of the '{@link #getMediatorStatement() <em>Mediator Statement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMediatorStatement()
   * @generated
   * @ordered
   */
  protected static final MediatorType MEDIATOR_STATEMENT_EDEFAULT = MediatorType.LOG;

  /**
   * The cached value of the '{@link #getMediatorStatement() <em>Mediator Statement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMediatorStatement()
   * @generated
   * @ordered
   */
  protected MediatorType mediatorStatement = MEDIATOR_STATEMENT_EDEFAULT;

  /**
   * The default value of the '{@link #getConfig() <em>Config</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConfig()
   * @generated
   * @ordered
   */
  protected static final String CONFIG_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getConfig() <em>Config</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConfig()
   * @generated
   * @ordered
   */
  protected String config = CONFIG_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MediatorStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.MEDIATOR_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MediatorType getMediatorStatement()
  {
    return mediatorStatement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMediatorStatement(MediatorType newMediatorStatement)
  {
    MediatorType oldMediatorStatement = mediatorStatement;
    mediatorStatement = newMediatorStatement == null ? MEDIATOR_STATEMENT_EDEFAULT : newMediatorStatement;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.MEDIATOR_STATEMENT__MEDIATOR_STATEMENT, oldMediatorStatement, mediatorStatement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getConfig()
  {
    return config;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setConfig(String newConfig)
  {
    String oldConfig = config;
    config = newConfig;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.MEDIATOR_STATEMENT__CONFIG, oldConfig, config));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.MEDIATOR_STATEMENT__MEDIATOR_STATEMENT:
        return getMediatorStatement();
      case MyDslPackage.MEDIATOR_STATEMENT__CONFIG:
        return getConfig();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.MEDIATOR_STATEMENT__MEDIATOR_STATEMENT:
        setMediatorStatement((MediatorType)newValue);
        return;
      case MyDslPackage.MEDIATOR_STATEMENT__CONFIG:
        setConfig((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.MEDIATOR_STATEMENT__MEDIATOR_STATEMENT:
        setMediatorStatement(MEDIATOR_STATEMENT_EDEFAULT);
        return;
      case MyDslPackage.MEDIATOR_STATEMENT__CONFIG:
        setConfig(CONFIG_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.MEDIATOR_STATEMENT__MEDIATOR_STATEMENT:
        return mediatorStatement != MEDIATOR_STATEMENT_EDEFAULT;
      case MyDslPackage.MEDIATOR_STATEMENT__CONFIG:
        return CONFIG_EDEFAULT == null ? config != null : !CONFIG_EDEFAULT.equals(config);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (mediatorStatement: ");
    result.append(mediatorStatement);
    result.append(", config: ");
    result.append(config);
    result.append(')');
    return result.toString();
  }

} //MediatorStatementImpl
