/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Inject
	private MyDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
					put(grammarAccess.getProcessingStatementAccess().getAlternatives_3(), "rule__ProcessingStatement__Alternatives_3");
					put(grammarAccess.getParticipantStatementAccess().getAlternatives(), "rule__ParticipantStatement__Alternatives");
					put(grammarAccess.getParticipantTypeAccess().getAlternatives(), "rule__ParticipantType__Alternatives");
					put(grammarAccess.getMediatorTypeAccess().getAlternatives(), "rule__MediatorType__Alternatives");
					put(grammarAccess.getMediatorStatementAccess().getGroup(), "rule__MediatorStatement__Group__0");
					put(grammarAccess.getProcessingStatementAccess().getGroup(), "rule__ProcessingStatement__Group__0");
					put(grammarAccess.getProcessingStatementAccess().getGroup_3_1(), "rule__ProcessingStatement__Group_3_1__0");
					put(grammarAccess.getRoutingStatementAccess().getGroup(), "rule__RoutingStatement__Group__0");
					put(grammarAccess.getParallelStatementAccess().getGroup(), "rule__ParallelStatement__Group__0");
					put(grammarAccess.getParallelStatementAccess().getGroup_2(), "rule__ParallelStatement__Group_2__0");
					put(grammarAccess.getIfStatementAccess().getGroup(), "rule__IfStatement__Group__0");
					put(grammarAccess.getIfStatementAccess().getGroup_16(), "rule__IfStatement__Group_16__0");
					put(grammarAccess.getLoopStatementAccess().getGroup(), "rule__LoopStatement__Group__0");
					put(grammarAccess.getGroupStatementAccess().getGroup(), "rule__GroupStatement__Group__0");
					put(grammarAccess.getRefStatementAccess().getGroup(), "rule__RefStatement__Group__0");
					put(grammarAccess.getParticipantStatementAccess().getGroup_0(), "rule__ParticipantStatement__Group_0__0");
					put(grammarAccess.getParticipantStatementAccess().getGroup_1(), "rule__ParticipantStatement__Group_1__0");
					put(grammarAccess.getParticipantStatementAccess().getGroup_2(), "rule__ParticipantStatement__Group_2__0");
					put(grammarAccess.getOutboundEndpointDefAccess().getGroup(), "rule__OutboundEndpointDef__Group__0");
					put(grammarAccess.getInboundEndpointDefAccess().getGroup(), "rule__InboundEndpointDef__Group__0");
					put(grammarAccess.getModelAccess().getParticipantsAssignment_0(), "rule__Model__ParticipantsAssignment_0");
					put(grammarAccess.getModelAccess().getStatementsAssignment_1(), "rule__Model__StatementsAssignment_1");
					put(grammarAccess.getMediatorStatementAccess().getMediatorStatementAssignment_0(), "rule__MediatorStatement__MediatorStatementAssignment_0");
					put(grammarAccess.getMediatorStatementAccess().getConfigAssignment_2(), "rule__MediatorStatement__ConfigAssignment_2");
					put(grammarAccess.getProcessingStatementAccess().getNameAssignment_2(), "rule__ProcessingStatement__NameAssignment_2");
					put(grammarAccess.getProcessingStatementAccess().getConfigsAssignment_3_1_1(), "rule__ProcessingStatement__ConfigsAssignment_3_1_1");
					put(grammarAccess.getRoutingStatementAccess().getSourceAssignment_0(), "rule__RoutingStatement__SourceAssignment_0");
					put(grammarAccess.getRoutingStatementAccess().getTargetAssignment_2(), "rule__RoutingStatement__TargetAssignment_2");
					put(grammarAccess.getRoutingStatementAccess().getActionAssignment_4(), "rule__RoutingStatement__ActionAssignment_4");
					put(grammarAccess.getParallelStatementAccess().getParstatementsAssignment_1(), "rule__ParallelStatement__ParstatementsAssignment_1");
					put(grammarAccess.getParallelStatementAccess().getElsestatementsAssignment_2_1(), "rule__ParallelStatement__ElsestatementsAssignment_2_1");
					put(grammarAccess.getIfStatementAccess().getRouteIdAssignment_5(), "rule__IfStatement__RouteIdAssignment_5");
					put(grammarAccess.getIfStatementAccess().getTransportAssignment_7(), "rule__IfStatement__TransportAssignment_7");
					put(grammarAccess.getIfStatementAccess().getPatternAssignment_12(), "rule__IfStatement__PatternAssignment_12");
					put(grammarAccess.getIfStatementAccess().getAltstatementsAssignment_15(), "rule__IfStatement__AltstatementsAssignment_15");
					put(grammarAccess.getIfStatementAccess().getElsestatementsAssignment_16_1(), "rule__IfStatement__ElsestatementsAssignment_16_1");
					put(grammarAccess.getLoopStatementAccess().getNameAssignment_1(), "rule__LoopStatement__NameAssignment_1");
					put(grammarAccess.getGroupStatementAccess().getNameAssignment_1(), "rule__GroupStatement__NameAssignment_1");
					put(grammarAccess.getRefStatementAccess().getNameAssignment_1(), "rule__RefStatement__NameAssignment_1");
					put(grammarAccess.getParticipantStatementAccess().getNameAssignment_0_1(), "rule__ParticipantStatement__NameAssignment_0_1");
					put(grammarAccess.getParticipantStatementAccess().getParticipantTypeAssignment_0_3(), "rule__ParticipantStatement__ParticipantTypeAssignment_0_3");
					put(grammarAccess.getParticipantStatementAccess().getDescriptionAssignment_0_5(), "rule__ParticipantStatement__DescriptionAssignment_0_5");
					put(grammarAccess.getParticipantStatementAccess().getNameAssignment_1_1(), "rule__ParticipantStatement__NameAssignment_1_1");
					put(grammarAccess.getParticipantStatementAccess().getOutboundsAssignment_1_3(), "rule__ParticipantStatement__OutboundsAssignment_1_3");
					put(grammarAccess.getParticipantStatementAccess().getNameAssignment_2_1(), "rule__ParticipantStatement__NameAssignment_2_1");
					put(grammarAccess.getParticipantStatementAccess().getInboundsAssignment_2_3(), "rule__ParticipantStatement__InboundsAssignment_2_3");
					put(grammarAccess.getOutboundEndpointDefAccess().getProtocolAssignment_4(), "rule__OutboundEndpointDef__ProtocolAssignment_4");
					put(grammarAccess.getOutboundEndpointDefAccess().getHostAssignment_9(), "rule__OutboundEndpointDef__HostAssignment_9");
					put(grammarAccess.getInboundEndpointDefAccess().getProtocolAssignment_4(), "rule__InboundEndpointDef__ProtocolAssignment_4");
					put(grammarAccess.getInboundEndpointDefAccess().getPortAssignment_9(), "rule__InboundEndpointDef__PortAssignment_9");
					put(grammarAccess.getInboundEndpointDefAccess().getContextAssignment_14(), "rule__InboundEndpointDef__ContextAssignment_14");
					put(grammarAccess.getModelAccess().getUnorderedGroup(), "rule__Model__UnorderedGroup");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalMyDslParser typedParser = (InternalMyDslParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
