/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IfStatement#getRouteId <em>Route Id</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IfStatement#getTransport <em>Transport</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IfStatement#getPattern <em>Pattern</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IfStatement#getAltstatements <em>Altstatements</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IfStatement#getElsestatements <em>Elsestatements</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIfStatement()
 * @model
 * @generated
 */
public interface IfStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Route Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Route Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Route Id</em>' attribute.
   * @see #setRouteId(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIfStatement_RouteId()
   * @model
   * @generated
   */
  String getRouteId();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IfStatement#getRouteId <em>Route Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Route Id</em>' attribute.
   * @see #getRouteId()
   * @generated
   */
  void setRouteId(String value);

  /**
   * Returns the value of the '<em><b>Transport</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Transport</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transport</em>' attribute.
   * @see #setTransport(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIfStatement_Transport()
   * @model
   * @generated
   */
  String getTransport();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IfStatement#getTransport <em>Transport</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transport</em>' attribute.
   * @see #getTransport()
   * @generated
   */
  void setTransport(String value);

  /**
   * Returns the value of the '<em><b>Pattern</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pattern</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pattern</em>' attribute.
   * @see #setPattern(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIfStatement_Pattern()
   * @model
   * @generated
   */
  String getPattern();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IfStatement#getPattern <em>Pattern</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pattern</em>' attribute.
   * @see #getPattern()
   * @generated
   */
  void setPattern(String value);

  /**
   * Returns the value of the '<em><b>Altstatements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Statement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Altstatements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Altstatements</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIfStatement_Altstatements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getAltstatements();

  /**
   * Returns the value of the '<em><b>Elsestatements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Statement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elsestatements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elsestatements</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIfStatement_Elsestatements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getElsestatements();

} // IfStatement
