/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Mediator Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMediatorType()
 * @model
 * @generated
 */
public enum MediatorType implements Enumerator
{
  /**
   * The '<em><b>LOG</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LOG_VALUE
   * @generated
   * @ordered
   */
  LOG(0, "LOG", "log"),

  /**
   * The '<em><b>CALL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CALL_VALUE
   * @generated
   * @ordered
   */
  CALL(1, "CALL", "call"),

  /**
   * The '<em><b>RESPOND</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RESPOND_VALUE
   * @generated
   * @ordered
   */
  RESPOND(2, "RESPOND", "respond"),

  /**
   * The '<em><b>FILTER</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FILTER_VALUE
   * @generated
   * @ordered
   */
  FILTER(3, "FILTER", "filter"),

  /**
   * The '<em><b>TRANSFORM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TRANSFORM_VALUE
   * @generated
   * @ordered
   */
  TRANSFORM(4, "TRANSFORM", "transform"),

  /**
   * The '<em><b>ENRICH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ENRICH_VALUE
   * @generated
   * @ordered
   */
  ENRICH(5, "ENRICH", "enrich"),

  /**
   * The '<em><b>EXTERNAL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EXTERNAL_VALUE
   * @generated
   * @ordered
   */
  EXTERNAL(6, "EXTERNAL", "external");

  /**
   * The '<em><b>LOG</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LOG</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LOG
   * @model literal="log"
   * @generated
   * @ordered
   */
  public static final int LOG_VALUE = 0;

  /**
   * The '<em><b>CALL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>CALL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CALL
   * @model literal="call"
   * @generated
   * @ordered
   */
  public static final int CALL_VALUE = 1;

  /**
   * The '<em><b>RESPOND</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>RESPOND</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #RESPOND
   * @model literal="respond"
   * @generated
   * @ordered
   */
  public static final int RESPOND_VALUE = 2;

  /**
   * The '<em><b>FILTER</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>FILTER</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FILTER
   * @model literal="filter"
   * @generated
   * @ordered
   */
  public static final int FILTER_VALUE = 3;

  /**
   * The '<em><b>TRANSFORM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>TRANSFORM</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TRANSFORM
   * @model literal="transform"
   * @generated
   * @ordered
   */
  public static final int TRANSFORM_VALUE = 4;

  /**
   * The '<em><b>ENRICH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ENRICH</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ENRICH
   * @model literal="enrich"
   * @generated
   * @ordered
   */
  public static final int ENRICH_VALUE = 5;

  /**
   * The '<em><b>EXTERNAL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EXTERNAL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EXTERNAL
   * @model literal="external"
   * @generated
   * @ordered
   */
  public static final int EXTERNAL_VALUE = 6;

  /**
   * An array of all the '<em><b>Mediator Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final MediatorType[] VALUES_ARRAY =
    new MediatorType[]
    {
      LOG,
      CALL,
      RESPOND,
      FILTER,
      TRANSFORM,
      ENRICH,
      EXTERNAL,
    };

  /**
   * A public read-only list of all the '<em><b>Mediator Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<MediatorType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Mediator Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static MediatorType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      MediatorType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Mediator Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static MediatorType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      MediatorType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Mediator Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static MediatorType get(int value)
  {
    switch (value)
    {
      case LOG_VALUE: return LOG;
      case CALL_VALUE: return CALL;
      case RESPOND_VALUE: return RESPOND;
      case FILTER_VALUE: return FILTER;
      case TRANSFORM_VALUE: return TRANSFORM;
      case ENRICH_VALUE: return ENRICH;
      case EXTERNAL_VALUE: return EXTERNAL;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private MediatorType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //MediatorType
