/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Participants</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PARTICIPANTS = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__STATEMENTS = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.StatementImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.MediatorStatementImpl <em>Mediator Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.MediatorStatementImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMediatorStatement()
   * @generated
   */
  int MEDIATOR_STATEMENT = 2;

  /**
   * The feature id for the '<em><b>Mediator Statement</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEDIATOR_STATEMENT__MEDIATOR_STATEMENT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Config</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEDIATOR_STATEMENT__CONFIG = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Mediator Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEDIATOR_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ProcessingStatementImpl <em>Processing Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ProcessingStatementImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getProcessingStatement()
   * @generated
   */
  int PROCESSING_STATEMENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESSING_STATEMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Configs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESSING_STATEMENT__CONFIGS = 1;

  /**
   * The number of structural features of the '<em>Processing Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESSING_STATEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RoutingStatementImpl <em>Routing Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RoutingStatementImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRoutingStatement()
   * @generated
   */
  int ROUTING_STATEMENT = 4;

  /**
   * The feature id for the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTING_STATEMENT__SOURCE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTING_STATEMENT__TARGET = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTING_STATEMENT__ACTION = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Routing Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTING_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ParallelStatementImpl <em>Parallel Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ParallelStatementImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getParallelStatement()
   * @generated
   */
  int PARALLEL_STATEMENT = 5;

  /**
   * The feature id for the '<em><b>Parstatements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARALLEL_STATEMENT__PARSTATEMENTS = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Elsestatements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARALLEL_STATEMENT__ELSESTATEMENTS = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Parallel Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARALLEL_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.IfStatementImpl <em>If Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.IfStatementImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIfStatement()
   * @generated
   */
  int IF_STATEMENT = 6;

  /**
   * The feature id for the '<em><b>Route Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STATEMENT__ROUTE_ID = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Transport</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STATEMENT__TRANSPORT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Pattern</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STATEMENT__PATTERN = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Altstatements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STATEMENT__ALTSTATEMENTS = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Elsestatements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STATEMENT__ELSESTATEMENTS = STATEMENT_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>If Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LoopStatementImpl <em>Loop Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LoopStatementImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLoopStatement()
   * @generated
   */
  int LOOP_STATEMENT = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_STATEMENT__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Loop Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.GroupStatementImpl <em>Group Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.GroupStatementImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getGroupStatement()
   * @generated
   */
  int GROUP_STATEMENT = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_STATEMENT__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Group Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RefStatementImpl <em>Ref Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RefStatementImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRefStatement()
   * @generated
   */
  int REF_STATEMENT = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REF_STATEMENT__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Ref Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REF_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ParticipantStatementImpl <em>Participant Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ParticipantStatementImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getParticipantStatement()
   * @generated
   */
  int PARTICIPANT_STATEMENT = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANT_STATEMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Participant Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANT_STATEMENT__PARTICIPANT_TYPE = 1;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANT_STATEMENT__DESCRIPTION = 2;

  /**
   * The feature id for the '<em><b>Outbounds</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANT_STATEMENT__OUTBOUNDS = 3;

  /**
   * The feature id for the '<em><b>Inbounds</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANT_STATEMENT__INBOUNDS = 4;

  /**
   * The number of structural features of the '<em>Participant Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANT_STATEMENT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.OutboundEndpointDefImpl <em>Outbound Endpoint Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.OutboundEndpointDefImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOutboundEndpointDef()
   * @generated
   */
  int OUTBOUND_ENDPOINT_DEF = 11;

  /**
   * The feature id for the '<em><b>Protocol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTBOUND_ENDPOINT_DEF__PROTOCOL = 0;

  /**
   * The feature id for the '<em><b>Host</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTBOUND_ENDPOINT_DEF__HOST = 1;

  /**
   * The number of structural features of the '<em>Outbound Endpoint Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTBOUND_ENDPOINT_DEF_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.InboundEndpointDefImpl <em>Inbound Endpoint Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.InboundEndpointDefImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInboundEndpointDef()
   * @generated
   */
  int INBOUND_ENDPOINT_DEF = 12;

  /**
   * The feature id for the '<em><b>Protocol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INBOUND_ENDPOINT_DEF__PROTOCOL = 0;

  /**
   * The feature id for the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INBOUND_ENDPOINT_DEF__PORT = 1;

  /**
   * The feature id for the '<em><b>Context</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INBOUND_ENDPOINT_DEF__CONTEXT = 2;

  /**
   * The number of structural features of the '<em>Inbound Endpoint Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INBOUND_ENDPOINT_DEF_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.ParticipantType <em>Participant Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.ParticipantType
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getParticipantType()
   * @generated
   */
  int PARTICIPANT_TYPE = 13;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.MediatorType <em>Mediator Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.MediatorType
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMediatorType()
   * @generated
   */
  int MEDIATOR_TYPE = 14;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getParticipants <em>Participants</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Participants</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getParticipants()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Participants();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getStatements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Statements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see org.xtext.example.mydsl.myDsl.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.MediatorStatement <em>Mediator Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mediator Statement</em>'.
   * @see org.xtext.example.mydsl.myDsl.MediatorStatement
   * @generated
   */
  EClass getMediatorStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.MediatorStatement#getMediatorStatement <em>Mediator Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mediator Statement</em>'.
   * @see org.xtext.example.mydsl.myDsl.MediatorStatement#getMediatorStatement()
   * @see #getMediatorStatement()
   * @generated
   */
  EAttribute getMediatorStatement_MediatorStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.MediatorStatement#getConfig <em>Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Config</em>'.
   * @see org.xtext.example.mydsl.myDsl.MediatorStatement#getConfig()
   * @see #getMediatorStatement()
   * @generated
   */
  EAttribute getMediatorStatement_Config();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ProcessingStatement <em>Processing Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Processing Statement</em>'.
   * @see org.xtext.example.mydsl.myDsl.ProcessingStatement
   * @generated
   */
  EClass getProcessingStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ProcessingStatement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.ProcessingStatement#getName()
   * @see #getProcessingStatement()
   * @generated
   */
  EAttribute getProcessingStatement_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ProcessingStatement#getConfigs <em>Configs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Configs</em>'.
   * @see org.xtext.example.mydsl.myDsl.ProcessingStatement#getConfigs()
   * @see #getProcessingStatement()
   * @generated
   */
  EAttribute getProcessingStatement_Configs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.RoutingStatement <em>Routing Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Routing Statement</em>'.
   * @see org.xtext.example.mydsl.myDsl.RoutingStatement
   * @generated
   */
  EClass getRoutingStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.RoutingStatement#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source</em>'.
   * @see org.xtext.example.mydsl.myDsl.RoutingStatement#getSource()
   * @see #getRoutingStatement()
   * @generated
   */
  EAttribute getRoutingStatement_Source();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.RoutingStatement#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see org.xtext.example.mydsl.myDsl.RoutingStatement#getTarget()
   * @see #getRoutingStatement()
   * @generated
   */
  EAttribute getRoutingStatement_Target();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.RoutingStatement#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action</em>'.
   * @see org.xtext.example.mydsl.myDsl.RoutingStatement#getAction()
   * @see #getRoutingStatement()
   * @generated
   */
  EAttribute getRoutingStatement_Action();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ParallelStatement <em>Parallel Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parallel Statement</em>'.
   * @see org.xtext.example.mydsl.myDsl.ParallelStatement
   * @generated
   */
  EClass getParallelStatement();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.ParallelStatement#getParstatements <em>Parstatements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parstatements</em>'.
   * @see org.xtext.example.mydsl.myDsl.ParallelStatement#getParstatements()
   * @see #getParallelStatement()
   * @generated
   */
  EReference getParallelStatement_Parstatements();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.ParallelStatement#getElsestatements <em>Elsestatements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elsestatements</em>'.
   * @see org.xtext.example.mydsl.myDsl.ParallelStatement#getElsestatements()
   * @see #getParallelStatement()
   * @generated
   */
  EReference getParallelStatement_Elsestatements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.IfStatement <em>If Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If Statement</em>'.
   * @see org.xtext.example.mydsl.myDsl.IfStatement
   * @generated
   */
  EClass getIfStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.IfStatement#getRouteId <em>Route Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Route Id</em>'.
   * @see org.xtext.example.mydsl.myDsl.IfStatement#getRouteId()
   * @see #getIfStatement()
   * @generated
   */
  EAttribute getIfStatement_RouteId();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.IfStatement#getTransport <em>Transport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Transport</em>'.
   * @see org.xtext.example.mydsl.myDsl.IfStatement#getTransport()
   * @see #getIfStatement()
   * @generated
   */
  EAttribute getIfStatement_Transport();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.IfStatement#getPattern <em>Pattern</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pattern</em>'.
   * @see org.xtext.example.mydsl.myDsl.IfStatement#getPattern()
   * @see #getIfStatement()
   * @generated
   */
  EAttribute getIfStatement_Pattern();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.IfStatement#getAltstatements <em>Altstatements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Altstatements</em>'.
   * @see org.xtext.example.mydsl.myDsl.IfStatement#getAltstatements()
   * @see #getIfStatement()
   * @generated
   */
  EReference getIfStatement_Altstatements();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.IfStatement#getElsestatements <em>Elsestatements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elsestatements</em>'.
   * @see org.xtext.example.mydsl.myDsl.IfStatement#getElsestatements()
   * @see #getIfStatement()
   * @generated
   */
  EReference getIfStatement_Elsestatements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.LoopStatement <em>Loop Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Loop Statement</em>'.
   * @see org.xtext.example.mydsl.myDsl.LoopStatement
   * @generated
   */
  EClass getLoopStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.LoopStatement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.LoopStatement#getName()
   * @see #getLoopStatement()
   * @generated
   */
  EAttribute getLoopStatement_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.GroupStatement <em>Group Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Group Statement</em>'.
   * @see org.xtext.example.mydsl.myDsl.GroupStatement
   * @generated
   */
  EClass getGroupStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.GroupStatement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.GroupStatement#getName()
   * @see #getGroupStatement()
   * @generated
   */
  EAttribute getGroupStatement_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.RefStatement <em>Ref Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ref Statement</em>'.
   * @see org.xtext.example.mydsl.myDsl.RefStatement
   * @generated
   */
  EClass getRefStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.RefStatement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.RefStatement#getName()
   * @see #getRefStatement()
   * @generated
   */
  EAttribute getRefStatement_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ParticipantStatement <em>Participant Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Participant Statement</em>'.
   * @see org.xtext.example.mydsl.myDsl.ParticipantStatement
   * @generated
   */
  EClass getParticipantStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ParticipantStatement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.ParticipantStatement#getName()
   * @see #getParticipantStatement()
   * @generated
   */
  EAttribute getParticipantStatement_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ParticipantStatement#getParticipantType <em>Participant Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Participant Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.ParticipantStatement#getParticipantType()
   * @see #getParticipantStatement()
   * @generated
   */
  EAttribute getParticipantStatement_ParticipantType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ParticipantStatement#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.example.mydsl.myDsl.ParticipantStatement#getDescription()
   * @see #getParticipantStatement()
   * @generated
   */
  EAttribute getParticipantStatement_Description();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ParticipantStatement#getOutbounds <em>Outbounds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Outbounds</em>'.
   * @see org.xtext.example.mydsl.myDsl.ParticipantStatement#getOutbounds()
   * @see #getParticipantStatement()
   * @generated
   */
  EReference getParticipantStatement_Outbounds();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ParticipantStatement#getInbounds <em>Inbounds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Inbounds</em>'.
   * @see org.xtext.example.mydsl.myDsl.ParticipantStatement#getInbounds()
   * @see #getParticipantStatement()
   * @generated
   */
  EReference getParticipantStatement_Inbounds();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.OutboundEndpointDef <em>Outbound Endpoint Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Outbound Endpoint Def</em>'.
   * @see org.xtext.example.mydsl.myDsl.OutboundEndpointDef
   * @generated
   */
  EClass getOutboundEndpointDef();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.OutboundEndpointDef#getProtocol <em>Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Protocol</em>'.
   * @see org.xtext.example.mydsl.myDsl.OutboundEndpointDef#getProtocol()
   * @see #getOutboundEndpointDef()
   * @generated
   */
  EAttribute getOutboundEndpointDef_Protocol();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.OutboundEndpointDef#getHost <em>Host</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Host</em>'.
   * @see org.xtext.example.mydsl.myDsl.OutboundEndpointDef#getHost()
   * @see #getOutboundEndpointDef()
   * @generated
   */
  EAttribute getOutboundEndpointDef_Host();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.InboundEndpointDef <em>Inbound Endpoint Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inbound Endpoint Def</em>'.
   * @see org.xtext.example.mydsl.myDsl.InboundEndpointDef
   * @generated
   */
  EClass getInboundEndpointDef();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.InboundEndpointDef#getProtocol <em>Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Protocol</em>'.
   * @see org.xtext.example.mydsl.myDsl.InboundEndpointDef#getProtocol()
   * @see #getInboundEndpointDef()
   * @generated
   */
  EAttribute getInboundEndpointDef_Protocol();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.InboundEndpointDef#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Port</em>'.
   * @see org.xtext.example.mydsl.myDsl.InboundEndpointDef#getPort()
   * @see #getInboundEndpointDef()
   * @generated
   */
  EAttribute getInboundEndpointDef_Port();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.InboundEndpointDef#getContext <em>Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Context</em>'.
   * @see org.xtext.example.mydsl.myDsl.InboundEndpointDef#getContext()
   * @see #getInboundEndpointDef()
   * @generated
   */
  EAttribute getInboundEndpointDef_Context();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.myDsl.ParticipantType <em>Participant Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Participant Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.ParticipantType
   * @generated
   */
  EEnum getParticipantType();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.myDsl.MediatorType <em>Mediator Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Mediator Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.MediatorType
   * @generated
   */
  EEnum getMediatorType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Participants</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__PARTICIPANTS = eINSTANCE.getModel_Participants();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__STATEMENTS = eINSTANCE.getModel_Statements();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.StatementImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.MediatorStatementImpl <em>Mediator Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.MediatorStatementImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMediatorStatement()
     * @generated
     */
    EClass MEDIATOR_STATEMENT = eINSTANCE.getMediatorStatement();

    /**
     * The meta object literal for the '<em><b>Mediator Statement</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEDIATOR_STATEMENT__MEDIATOR_STATEMENT = eINSTANCE.getMediatorStatement_MediatorStatement();

    /**
     * The meta object literal for the '<em><b>Config</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEDIATOR_STATEMENT__CONFIG = eINSTANCE.getMediatorStatement_Config();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ProcessingStatementImpl <em>Processing Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ProcessingStatementImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getProcessingStatement()
     * @generated
     */
    EClass PROCESSING_STATEMENT = eINSTANCE.getProcessingStatement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESSING_STATEMENT__NAME = eINSTANCE.getProcessingStatement_Name();

    /**
     * The meta object literal for the '<em><b>Configs</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESSING_STATEMENT__CONFIGS = eINSTANCE.getProcessingStatement_Configs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RoutingStatementImpl <em>Routing Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RoutingStatementImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRoutingStatement()
     * @generated
     */
    EClass ROUTING_STATEMENT = eINSTANCE.getRoutingStatement();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROUTING_STATEMENT__SOURCE = eINSTANCE.getRoutingStatement_Source();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROUTING_STATEMENT__TARGET = eINSTANCE.getRoutingStatement_Target();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROUTING_STATEMENT__ACTION = eINSTANCE.getRoutingStatement_Action();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ParallelStatementImpl <em>Parallel Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ParallelStatementImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getParallelStatement()
     * @generated
     */
    EClass PARALLEL_STATEMENT = eINSTANCE.getParallelStatement();

    /**
     * The meta object literal for the '<em><b>Parstatements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARALLEL_STATEMENT__PARSTATEMENTS = eINSTANCE.getParallelStatement_Parstatements();

    /**
     * The meta object literal for the '<em><b>Elsestatements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARALLEL_STATEMENT__ELSESTATEMENTS = eINSTANCE.getParallelStatement_Elsestatements();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.IfStatementImpl <em>If Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.IfStatementImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIfStatement()
     * @generated
     */
    EClass IF_STATEMENT = eINSTANCE.getIfStatement();

    /**
     * The meta object literal for the '<em><b>Route Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IF_STATEMENT__ROUTE_ID = eINSTANCE.getIfStatement_RouteId();

    /**
     * The meta object literal for the '<em><b>Transport</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IF_STATEMENT__TRANSPORT = eINSTANCE.getIfStatement_Transport();

    /**
     * The meta object literal for the '<em><b>Pattern</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IF_STATEMENT__PATTERN = eINSTANCE.getIfStatement_Pattern();

    /**
     * The meta object literal for the '<em><b>Altstatements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_STATEMENT__ALTSTATEMENTS = eINSTANCE.getIfStatement_Altstatements();

    /**
     * The meta object literal for the '<em><b>Elsestatements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_STATEMENT__ELSESTATEMENTS = eINSTANCE.getIfStatement_Elsestatements();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LoopStatementImpl <em>Loop Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LoopStatementImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLoopStatement()
     * @generated
     */
    EClass LOOP_STATEMENT = eINSTANCE.getLoopStatement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOP_STATEMENT__NAME = eINSTANCE.getLoopStatement_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.GroupStatementImpl <em>Group Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.GroupStatementImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getGroupStatement()
     * @generated
     */
    EClass GROUP_STATEMENT = eINSTANCE.getGroupStatement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GROUP_STATEMENT__NAME = eINSTANCE.getGroupStatement_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RefStatementImpl <em>Ref Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RefStatementImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRefStatement()
     * @generated
     */
    EClass REF_STATEMENT = eINSTANCE.getRefStatement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REF_STATEMENT__NAME = eINSTANCE.getRefStatement_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ParticipantStatementImpl <em>Participant Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ParticipantStatementImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getParticipantStatement()
     * @generated
     */
    EClass PARTICIPANT_STATEMENT = eINSTANCE.getParticipantStatement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTICIPANT_STATEMENT__NAME = eINSTANCE.getParticipantStatement_Name();

    /**
     * The meta object literal for the '<em><b>Participant Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTICIPANT_STATEMENT__PARTICIPANT_TYPE = eINSTANCE.getParticipantStatement_ParticipantType();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTICIPANT_STATEMENT__DESCRIPTION = eINSTANCE.getParticipantStatement_Description();

    /**
     * The meta object literal for the '<em><b>Outbounds</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARTICIPANT_STATEMENT__OUTBOUNDS = eINSTANCE.getParticipantStatement_Outbounds();

    /**
     * The meta object literal for the '<em><b>Inbounds</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARTICIPANT_STATEMENT__INBOUNDS = eINSTANCE.getParticipantStatement_Inbounds();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.OutboundEndpointDefImpl <em>Outbound Endpoint Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.OutboundEndpointDefImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOutboundEndpointDef()
     * @generated
     */
    EClass OUTBOUND_ENDPOINT_DEF = eINSTANCE.getOutboundEndpointDef();

    /**
     * The meta object literal for the '<em><b>Protocol</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTBOUND_ENDPOINT_DEF__PROTOCOL = eINSTANCE.getOutboundEndpointDef_Protocol();

    /**
     * The meta object literal for the '<em><b>Host</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTBOUND_ENDPOINT_DEF__HOST = eINSTANCE.getOutboundEndpointDef_Host();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.InboundEndpointDefImpl <em>Inbound Endpoint Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.InboundEndpointDefImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInboundEndpointDef()
     * @generated
     */
    EClass INBOUND_ENDPOINT_DEF = eINSTANCE.getInboundEndpointDef();

    /**
     * The meta object literal for the '<em><b>Protocol</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INBOUND_ENDPOINT_DEF__PROTOCOL = eINSTANCE.getInboundEndpointDef_Protocol();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INBOUND_ENDPOINT_DEF__PORT = eINSTANCE.getInboundEndpointDef_Port();

    /**
     * The meta object literal for the '<em><b>Context</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INBOUND_ENDPOINT_DEF__CONTEXT = eINSTANCE.getInboundEndpointDef_Context();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.ParticipantType <em>Participant Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.ParticipantType
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getParticipantType()
     * @generated
     */
    EEnum PARTICIPANT_TYPE = eINSTANCE.getParticipantType();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.MediatorType <em>Mediator Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.MediatorType
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMediatorType()
     * @generated
     */
    EEnum MEDIATOR_TYPE = eINSTANCE.getMediatorType();

  }

} //MyDslPackage
