/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Participant Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ParticipantStatement#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ParticipantStatement#getParticipantType <em>Participant Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ParticipantStatement#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ParticipantStatement#getOutbounds <em>Outbounds</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ParticipantStatement#getInbounds <em>Inbounds</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getParticipantStatement()
 * @model
 * @generated
 */
public interface ParticipantStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getParticipantStatement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ParticipantStatement#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Participant Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myDsl.ParticipantType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Participant Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Participant Type</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.ParticipantType
   * @see #setParticipantType(ParticipantType)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getParticipantStatement_ParticipantType()
   * @model
   * @generated
   */
  ParticipantType getParticipantType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ParticipantStatement#getParticipantType <em>Participant Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Participant Type</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.ParticipantType
   * @see #getParticipantType()
   * @generated
   */
  void setParticipantType(ParticipantType value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getParticipantStatement_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ParticipantStatement#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Outbounds</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Outbounds</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Outbounds</em>' containment reference.
   * @see #setOutbounds(OutboundEndpointDef)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getParticipantStatement_Outbounds()
   * @model containment="true"
   * @generated
   */
  OutboundEndpointDef getOutbounds();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ParticipantStatement#getOutbounds <em>Outbounds</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Outbounds</em>' containment reference.
   * @see #getOutbounds()
   * @generated
   */
  void setOutbounds(OutboundEndpointDef value);

  /**
   * Returns the value of the '<em><b>Inbounds</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Inbounds</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inbounds</em>' containment reference.
   * @see #setInbounds(InboundEndpointDef)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getParticipantStatement_Inbounds()
   * @model containment="true"
   * @generated
   */
  InboundEndpointDef getInbounds();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ParticipantStatement#getInbounds <em>Inbounds</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inbounds</em>' containment reference.
   * @see #getInbounds()
   * @generated
   */
  void setInbounds(InboundEndpointDef value);

} // ParticipantStatement
