/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Participant Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getParticipantType()
 * @model
 * @generated
 */
public enum ParticipantType implements Enumerator
{
  /**
   * The '<em><b>INTEGRATIONFLOW</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INTEGRATIONFLOW_VALUE
   * @generated
   * @ordered
   */
  INTEGRATIONFLOW(0, "INTEGRATIONFLOW", "IntegrationFlow"),

  /**
   * The '<em><b>INBOUNDENDPOINT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INBOUNDENDPOINT_VALUE
   * @generated
   * @ordered
   */
  INBOUNDENDPOINT(1, "INBOUNDENDPOINT", "InboundEndpoint"),

  /**
   * The '<em><b>OUTBOUNDENDPOINT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #OUTBOUNDENDPOINT_VALUE
   * @generated
   * @ordered
   */
  OUTBOUNDENDPOINT(2, "OUTBOUNDENDPOINT", "OutboundEndpoint"),

  /**
   * The '<em><b>PIPELINE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PIPELINE_VALUE
   * @generated
   * @ordered
   */
  PIPELINE(3, "PIPELINE", "Pipeline");

  /**
   * The '<em><b>INTEGRATIONFLOW</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INTEGRATIONFLOW</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INTEGRATIONFLOW
   * @model literal="IntegrationFlow"
   * @generated
   * @ordered
   */
  public static final int INTEGRATIONFLOW_VALUE = 0;

  /**
   * The '<em><b>INBOUNDENDPOINT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INBOUNDENDPOINT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INBOUNDENDPOINT
   * @model literal="InboundEndpoint"
   * @generated
   * @ordered
   */
  public static final int INBOUNDENDPOINT_VALUE = 1;

  /**
   * The '<em><b>OUTBOUNDENDPOINT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>OUTBOUNDENDPOINT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #OUTBOUNDENDPOINT
   * @model literal="OutboundEndpoint"
   * @generated
   * @ordered
   */
  public static final int OUTBOUNDENDPOINT_VALUE = 2;

  /**
   * The '<em><b>PIPELINE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>PIPELINE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PIPELINE
   * @model literal="Pipeline"
   * @generated
   * @ordered
   */
  public static final int PIPELINE_VALUE = 3;

  /**
   * An array of all the '<em><b>Participant Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final ParticipantType[] VALUES_ARRAY =
    new ParticipantType[]
    {
      INTEGRATIONFLOW,
      INBOUNDENDPOINT,
      OUTBOUNDENDPOINT,
      PIPELINE,
    };

  /**
   * A public read-only list of all the '<em><b>Participant Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<ParticipantType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Participant Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ParticipantType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ParticipantType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Participant Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ParticipantType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ParticipantType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Participant Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ParticipantType get(int value)
  {
    switch (value)
    {
      case INTEGRATIONFLOW_VALUE: return INTEGRATIONFLOW;
      case INBOUNDENDPOINT_VALUE: return INBOUNDENDPOINT;
      case OUTBOUNDENDPOINT_VALUE: return OUTBOUNDENDPOINT;
      case PIPELINE_VALUE: return PIPELINE;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private ParticipantType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //ParticipantType
